### PR TITLE
Update torrent library

### PR DESCRIPTION
**Pull request by julyworlds**
Use latest version of TorrentStream-Android and jlibtorrent

### CODE REVIEW

**Comment by julyworlds** [comment]
I saw that the TorrentStream and TorrentStreamServers are also forked, maybe its better to update them instead of using then as a submodule for the build? Let me know.

**Comment by ivan1986** [comment]
I try to merge, but author close https://github.com/TorrentStream/TorrentStream-Android/pull/81
because also need update torrent lib, i think maybe just put it to repo, as i do this with connectSDK,but project back to live now, and looks i was wrong
ok, i check how it workand merge

**Comment by ivan1986** [comment]
https://github.com/frostwire/frostwire-jlibtorrent/issues/274

**Comment by julyworlds** [comment]
I noticed that when I open a torrent it gets stuck in fetching magnet url, its like it can't resolve the magnet url. An after a while it starts resolving magnet urls and everything works fine. And it happens with every version of jlibtorrent, not only the latest one.

Would be interesting to test if the same problem happens if we use a .torrent file instead.

**Comment by julyworlds** [comment]
I saw a response about this other library working well https://github.com/aldenml/libtorrent4j

I will try to change the code to use that version instead. Closing the PR for now.

**Comment by ivan1986** [comment]
Thanks!
All work with new lib

**Comment by ivan1986** [comment]
build 0.3.5 and release on site
reddit now banned, try to recovery

**Comment by julyworlds** [comment]
I was testing it and trying to tweak a bit a few things, I will make another update soon. I noticed the loading bar was not working really well for example.

**Comment by julyworlds** [comment]
I gave up on updating the bar progress, its a bit weird. The initial progress goes to 100% because only the first blocks of the torrent file are selected to be downloaded, then the progress goes back to 2% because the entire file gets selected to be downloaded. To change that would have to change too many things in the library, so it will keep it as it is.

**Pull request merged**
